name: Deploy to Local Rancher Desktop

on:
  workflow_run:
    workflows:
      - CI/CD - Build, Test and Publish Images
    types:
      - completed

jobs:
  deploy-local:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Kubernetes status
        shell: powershell
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Apply Kubernetes manifests
        shell: powershell
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/backend.yaml
          kubectl apply -f k8s/frontend.yaml

      - name: Set new images from GHCR
        shell: powershell
        run: |
          kubectl set image deployment/backend backend="ghcr.io/${{ github.repository_owner }}/lab-ac-backend:${{ github.event.workflow_run.head_sha }}" -n lab-cloud-app
          kubectl set image deployment/frontend frontend="ghcr.io/${{ github.repository_owner }}/lab-ac-frontend:${{ github.event.workflow_run.head_sha }}" -n lab-cloud-app

      - name: Start application
        shell: powershell
        run: |
          kubectl scale deployment/postgres -n lab-cloud-app --replicas=1
          kubectl scale deployment/backend -n lab-cloud-app --replicas=2
          kubectl scale deployment/frontend -n lab-cloud-app --replicas=1

      - name: Wait for rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/postgres -n lab-cloud-app
          kubectl rollout status deployment/backend -n lab-cloud-app
          kubectl rollout status deployment/frontend -n lab-cloud-app

      - name: Show final status
        shell: powershell
        run: |
          kubectl get all -n lab-cloud-app