name: Deploy to Local Rancher Desktop

on:
  workflow_run:
    workflows:
      - CI/CD - Build, Test and Publish Images
    types:
      - completed

jobs:
  deploy-local:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply Kubernetes manifests
        shell: powershell
        run: |
          kubectl apply -f k8s/

      - name: Restart deployments
        shell: powershell
        run: |
          kubectl rollout restart deployment/postgres -n lab-k8s
          kubectl rollout restart deployment/backend -n lab-k8s
          kubectl rollout restart deployment/frontend -n lab-k8s

      - name: Wait for rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/postgres -n lab-k8s
          kubectl rollout status deployment/backend -n lab-k8s
          kubectl rollout status deployment/frontend -n lab-k8s

      - name: Show status
        shell: powershell
        run: |
          kubectl get all -n lab-k8s